### ISSUE TITLE
SetDefaultSignInAsAuthenticationType not debugging

### ISSUE THREAD

**Issue by itorian** [AndersAbel/SocialLoginWithoutIdentity#1]
'Owin.IAppBuilder' does not contain a definition for 'SetDefaultSignInAsAuthenticationType' and no extension method 'SetDefaultSignInAsAuthenticationType' accepting a first argument of type 'Owin.IAppBuilder' could be found (are you missing a using directive or an assembly reference?)   D:\web\demo\WebApplication3\WebApplication3\App_Start\Startup.cs

Please suggest.

**Comment by itorian** [comment]
Sorry, i was missing Microsoft.Owin.Security namespace, thanks for the identity less login. By the way, what if I would like to display login email address and login status on website. Also how to allow them logout. These are major questions needs to be answered.

**Comment by AndersAbel** [comment]
The logout would be handled the same as with any application using the application cookie. Just copy the logout method from a freshly created MVC 5.2 project.
