### ISSUE TITLE
Redirect URI did not match a registered redirect URI

### ISSUE THREAD

**Issue by xperiandri** [AndersAbel/SocialLoginWithoutIdentity#2]
I get such error
`The redirect URI in the request: http://localhost:62506/signin-google did not match a registered redirect URI.`

Could you tell me what can be wrong?

**Comment by AndersAbel** [comment]
You're missing some configuration on the Google side, you need to register the application with Google and set the parameters in Startup.Auth.GoogleSettings.cs

**Comment by xperiandri** [comment]
I did just that.
Created Web Client in Google, added Google+ API, set allowed redirect URI to http://localhost:62506/

**Comment by AndersAbel** [comment]
I think the allowed redirect URL should be http://localhost:62506/signin-google
