### ISSUE TITLE
authorize page returns an blank page

### ISSUE THREAD

**Issue by mspace23** [AndersAbel/SocialLoginWithoutIdentity#3]
Hello, the authorize page returns an blank page the url is
http://localhost:42000/Account/Login?ReturnUrl=%2FHome%2FSecure

Any Idea?
Thank you

**Comment by mspace23** [comment]
I manage to connect to my provider but  it brings null to string returnUrl in my ExternalLoginCallback. Can you help? thank you

**Comment by AndersAbel** [comment]
What provider are you using?

**Comment by mspace23** [comment]
Hello I am using JASIG CAS. I have installed the packages

**Comment by mspace23** [comment]
Hello I notice that I get the message from empty string returnUrl when I go from the login page to my provider when I click an [authorize] action and go to my provider, I also login correctly and then returns 
"The page isn't redirecting properly".
thank you

**Comment by mspace23** [comment]
I clear my cookies, but now after the login to my provider it returns "Server not found" Firefox can't find the server at login;jsessionid=64f6d8315def7d538dc3ae8deaf71103.". In Chrome in returns a blank page.

**Comment by mspace23** [comment]
I also tried it with Google. No luck. Same errors.
thank you

**Comment by AndersAbel** [comment]
The authentication middleware is responsible for preserving the AuthenticationProperties (including the returnUrl), so this looks like an issue with the provider. I can help you as a consultancy service, if that's interesting please mail me.

**Comment by mspace23** [comment]
Hello I found the solution! It works great now. Thank you for your offer!!
