### ISSUE TITLE
Return Email By Default?

### ISSUE THREAD

**Issue by chobo2** [AndersAbel/SocialLoginWithoutIdentity#4]
Hi

When the claims are returned back the information from google it has in the ((System.Security.Claims.ClaimsIdentity)User.Identity).Name = "chobo2". I want email address not the users name.

The Identity provider does have this information but it is under "identities" but this would require me to loop through and look for it. How can I make it the primary claim?

Also this seems to make a cookie for me. What happens if I want to add some more information to the cookie. I use to stick information like this in "data" area of the cookie but not sure how to do that here. Do I have to make a new cookie or grab the generated cookie and update it?

**Comment by AndersAbel** [comment]
You can change the "primary" claim by changing the `NameClaimType` property.
