### ISSUE TITLE
Iappbuilder noyt contain a defenition for SetDefaultSignInAsAuthenticationType 

### ISSUE THREAD

**Issue by UmaShakthi** [AndersAbel/SocialLoginWithoutIdentity#7]
In my MVC application , SetDefaultSignInAsAuthenticationType is not a name space for IappBuilder i use using Microsoft.Owin.Security; this namespace , but it was not enabled

**Comment by AndersAbel** [comment]
This is a very old sample that i do not maintain/support any more. I will archive the repo.
